# Generated by Django 4.0.1 on 2022-01-12 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Informe a data da doação')),
                ('justificativa', models.TextField(blank=True, help_text='Digite a justificativa da doação', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefe_da_familia', models.CharField(help_text='Digite o nome do chefe da família', max_length=200)),
                ('cpf', models.CharField(help_text='Digite o cpf do chefe da família', max_length=11)),
                ('endereco', models.CharField(help_text='Digite o endereço do chefe da família', max_length=200, verbose_name='endereço')),
                ('telefone1', phonenumber_field.modelfields.PhoneNumberField(help_text='Digite o telefone principal do chefe da família', max_length=128, region=None, verbose_name='telefone principal')),
                ('telefone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Digite o telefone secundário do chefe da família (opcional)', max_length=128, null=True, region=None, verbose_name='telefone secundário')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'ordering': ['chefe_da_familia'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do item', max_length=200)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, help_text='Digite o cpf do representante da entidade', max_length=11, null=True)),
                ('representante', models.ForeignKey(help_text='Selecione o usuário representante', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Representante de entidade',
                'verbose_name_plural': 'Representantes de entidades',
                'ordering': ['representante'],
            },
        ),
        migrations.CreateModel(
            name='ItensDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Digite a quantidade do item selecionado', null=True)),
                ('doacao', models.ForeignKey(help_text='Selecione a doação', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_de_doacoes.doacao')),
                ('item', models.ForeignKey(help_text='Selecione o item', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_de_doacoes.item')),
            ],
            options={
                'verbose_name': 'Item de doação',
                'verbose_name_plural': 'Itens de doações',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='IntegranteFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do integrante da família', max_length=200)),
                ('cpf', models.CharField(blank=True, help_text='Digite o cpf do integrante da família', max_length=11, null=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Digite o telefone do integrante da família (opcional)', max_length=128, null=True, region=None)),
                ('chefe_da_familia', models.ForeignKey(help_text='Selecione o chefe da família', on_delete=django.db.models.deletion.CASCADE, to='gestao_de_doacoes.familia')),
            ],
            options={
                'verbose_name': 'Integrante de família',
                'verbose_name_plural': 'Integrantes de famílias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(help_text='Digite o nome-fantasia da entidade', max_length=200)),
                ('cnpj', models.CharField(blank=True, help_text='Digite o cnpj da entidade', max_length=14, null=True)),
                ('endereco', models.CharField(help_text='Digite o email da entidade', max_length=200, verbose_name='endereço')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Digite o telefone da entidade (00)0 0000-0000 (Opcional)', max_length=128, null=True, region=None)),
                ('email', models.EmailField(help_text='Digite o email da entidade', max_length=254)),
                ('representante', models.ForeignKey(help_text='Selecione o representante da entidade', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_de_doacoes.representante')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.AddField(
            model_name='doacao',
            name='chefe_da_familia',
            field=models.ForeignKey(help_text='Selecione o chefe da família', on_delete=django.db.models.deletion.CASCADE, to='gestao_de_doacoes.familia'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='representante',
            field=models.ForeignKey(help_text='Selecione o usuário representante', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
