# Generated by Django 4.0.1 on 2022-01-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_doacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_cadastro',
        ),
    ]
