# Generated by Django 4.0.1 on 2022-01-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_doacoes', '0002_alter_representante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representante',
            options={'ordering': ['representante'], 'verbose_name': 'Representante de entidade', 'verbose_name_plural': 'Representantes de entidades'},
        ),
    ]
