# Generated by Django 4.0.1 on 2022-01-15 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_doacoes', '0002_remove_usuario_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Digite apenas números', regex='^[0-9]+$'), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
