# Generated by Django 4.0.1 on 2022-01-12 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_de_doacoes', '0003_alter_representante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representante',
            options={'ordering': ['nome'], 'verbose_name': 'Representante de entidade', 'verbose_name_plural': 'Representantes de entidades'},
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='representante',
        ),
        migrations.AddField(
            model_name='doacao',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='usuario',
            field=models.ForeignKey(help_text='Selecione o usuário representante', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='familia',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='integrantefamiliar',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='representante',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='representante',
            name='nome',
            field=models.CharField(help_text='Digite o nome do representante da entidade', max_length=200, null=True),
        ),
    ]
